export const monthlyRecapData = [
  {
    title: "Death Bed",
    artist: "Powfu",
    artwork: `${require("../../image/slideImg5.jpeg")}`,
    url: "https://samplesongs.netlify.app/Death%20Bed.mp3",
    id: "1",
    category: "Top Songs April 2023",
    downloads: 4800000,
  },
  {
    title: "Bad Liar",
    artist: "Imagine Dragons",
    artwork: `${require("../../image/radio-image.jpeg")}`,
    url: "https://samplesongs.netlify.app/Bad%20Liar.mp3",
    id: "2",
    category: "Top New Songs April 2023",
    downloads: 1100000,
  },
  {
    title: "Faded",
    artist: "Alan Walker",
    artwork: `${require("../../image/slideImg5.jpeg")}`,
    url: "https://samplesongs.netlify.app/Faded.mp3",
    id: "3",
    category: "Top Gospel Songs April 2023",
    downloads: 1300000,
  },
  {
    title: "Hate Me",
    artist: "Ellie Goulding",
    artwork: `${require("../../image/radio-image.jpeg")}`,
    url: "https://samplesongs.netlify.app/Hate%20Me.mp3",
    id: "4",
    category: "Top Afrobeats Songs April 2023",
    downloads: 409200,
  },
  {
    title: "Solo",
    artist: "Clean Bandit",
    artwork: `${require("../../image/slideImg5.jpeg")}`,
    url: "https://samplesongs.netlify.app/Solo.mp3",
    id: "5",
    category: "Top Hip Hop&Rap Songs April 2023",
    downloads: 228300,
  },
  {
    title: "Without Me",
    artist: "Halsey",
    artwork: `${require("../../image/radio-image.jpeg")}`,
    url: "https://samplesongs.netlify.app/Without%20Me.mp3",
    id: "6",
    category: "Top Free Songs April 2023",
    downloads: 4000000,
  },
];
